services:
  - type: web
    name: dashboard-ariete-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        fromDatabase:
          name: dashboard-ariete-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://dashboard-ariete.vercel.app
      - key: ESP32_API_KEY
        value: ariete-esp32-2025
      - key: JWT_EXPIRES_IN
        value: 7d



